
epochs: 5   #训练模型时，数据被遍历50轮次
learning_rate: 0.001  #学习率，控制模型参数更新的幅度。
batch_size: 64  #每次迭代使用64条数据组成一个批次。1W条数据，需要迭代约157次=10000/64

#一般先固定batch_size，调整learning_rate，观察损失函数曲线，若早期收敛停滞，可增大epochs或调整learning_rate
#损失函数：衡量模型预测结果与真实目标之间差异。收敛越慢代表差异越大。收敛越快代表差异逐步缩小。损失函数结果越小越接近真实值。
#优化模型就是最小化损失函数


